# Generated by Django 4.1.3 on 2022-11-23 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher', models.CharField(max_length=10)),
                ('Student', models.CharField(max_length=10)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
