# Generated by Django 4.1.3 on 2022-11-23 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='DateSent',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Rejected'), ('A', 'Accepted'), ('O', 'Old')], default='O', max_length=1),
        ),
    ]
