# Generated by Django 4.1.3 on 2022-11-28 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lessons.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_request_datesent_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='additionalInfo',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='request',
            name='durations',
            field=models.CharField(choices=[('1', 60), ('2', 30), ('3', 45), ('4', 50)], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='request',
            name='lesson_type',
            field=models.CharField(default='fuck serge', max_length=1000),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Rejected'), ('A', 'Accepted'), ('O', 'Old')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.CharField(choices=[(4, 'Friday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (0, 'Monday')], max_length=1)),
                ('time_of_lesson', models.DecimalField(decimal_places=2, max_digits=4)),
                ('teacher', models.CharField(max_length=10)),
                ('start_date', models.DateField(validators=[lessons.helpers.validateDate])),
                ('number_of_lessons', models.IntegerField(validators=[lessons.helpers.validateLessonNumber])),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='lessons.request')),
            ],
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
