# Generated by Django 4.1.3 on 2022-12-08 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_student_reference_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='special',
            new_name='speciality',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='nick_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='update_time',
        ),
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.IntegerField(choices=[(1, 'MRS'), (2, 'MR'), (3, 'MISS'), (4, 'MS')], default=1),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='lesson_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lessontype', to='lessons.lesson'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reference_number',
            field=models.CharField(default='1896', editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
