# Generated by Django 4.1.3 on 2022-12-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_rename_special_teacher_speciality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_num',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='student',
            name='reference_number',
            field=models.CharField(default='3282', editable=False, max_length=4),
        ),
    ]
