# Generated by Django 4.1.3 on 2022-12-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_remove_lesson_create_time_remove_lesson_interval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='director',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='icon_url',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='student',
            name='reference_number',
            field=models.CharField(max_length=4, unique=True, verbose_name='4053'),
        ),
    ]
