# Generated by Django 4.1.3 on 2022-12-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_remove_administrator_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reference_number',
            field=models.CharField(max_length=4, unique=True, verbose_name='1963'),
        ),
    ]
