# Generated by Django 4.1.3 on 2022-12-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_booking_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day_of_week',
            field=models.CharField(choices=[(3, 'Thursday'), (0, 'Monday'), (2, 'Wednesday'), (1, 'Tuesday'), (4, 'Friday')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
