# Generated by Django 4.1.3 on 2022-12-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_booking_day_of_week_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day_of_week',
            field=models.CharField(choices=[(2, 'Wednesday'), (0, 'Monday'), (3, 'Thursday'), (1, 'Tuesday'), (4, 'Friday')], max_length=1),
        ),
    ]
