# Generated by Django 4.1.3 on 2022-12-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_booking_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day_of_week',
            field=models.CharField(choices=[(2, 'Wednesday'), (4, 'Friday'), (3, 'Thursday'), (1, 'Tuesday'), (0, 'Monday')], max_length=1),
        ),
    ]
