# Generated by Django 4.1.3 on 2022-12-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_alter_booking_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day_of_week',
            field=models.CharField(choices=[(0, 'Monday'), (4, 'Friday'), (2, 'Wednesday'), (1, 'Tuesday'), (3, 'Thursday')], max_length=1),
        ),
    ]
