# Generated by Django 4.1.3 on 2022-12-08 15:42

from django.db import migrations, models
import lessons.models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_alter_student_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reference_number',
            field=models.CharField(default=lessons.models.random_id, max_length=4, null=True),
        ),
    ]
